### ISSUE TITLE
Redactar el punto 10.2 Componentes mas relevantes

### ISSUE THREAD

**Issue by antcarluq** [TFG-US-JL-AC/planning#65]
## Descripción
Esta tarea consiste en redactar el punto 10.2 Componentes mas relevantes. Se deben añadir varios puntos de componentes que ambos miembros del grupo consideren importantes. Antes de añadir uno preguntar al compañero si es un punto relevante.

> Aquí podéis poner el código del que os sentáis más orgullosos. No se trata de meter un listado con todo el código,
sino solamente comentar los módulos o componentes que habéis desarrollado, añadiendo algo de código fuente si es
necesario.
Usad una sección de nivel 3 para cada módulo. Es decir, 10.2 WebSockets, 10.3 Componente Proyectos, etc

Se recuerda que se debe usar el impersonal y que se deben referenciar las cosas. Si hay un elemento que todavía no se puede completar o hay que revisar se deberá marcar en rojo.

## Deadline
30 de Junio

**Comment by jualorper** [comment]
Buenas, 
He pensado de poner los siguientes componentes:
* Autenticación y autorización
* Componente de la vista principal
* Componente de edición colaborativa

He empezado con el de auth y el de edición colaborativa. Cualquier cosa me dices,
